/**
 * Chen volume catalog config (原书卷十四·陈诗).
 * Generated by scripts/generate-chen-config.mjs — edit overrides there, then regenerate.
 */
export const CHEN_CONFIG = {
  volume: "chen",
  dynasty: "陈",
  epubParts: [
    "text/part0020_split_000.html"
  ],
  expectedCount: 22,
  entries: [
  { slug: "du-qing-cao-hu", title: "渡青草湖", author: "阴铿", authorSlug: "yin-keng", mode: "single" },
  { slug: "guang-ling-an-song-bei-shi", title: "广陵岸送北使", author: "阴铿", authorSlug: "yin-keng", mode: "single" },
  { slug: "jiang-jin-song-liu-guang-lu-bu-ji", title: "江津送刘光禄不及", author: "阴铿", authorSlug: "yin-keng", mode: "single" },
  { slug: "he-fu-lang-sui-mu-hai-xiang-zhou", title: "和傅郎岁暮还湘州", author: "阴铿", authorSlug: "yin-keng", mode: "single" },
  { slug: "kai-shan-si", title: "开善寺", author: "阴铿", authorSlug: "yin-keng", mode: "single" },
  { slug: "chu-zi-ji-bei-men-xing", title: "出自蓟北门行", author: "徐陵", authorSlug: "xu-ling", mode: "single" },
  { slug: "bie-mao-yong-jia", title: "别毛永嘉", author: "徐陵", authorSlug: "xu-ling", mode: "single" },
  { slug: "xu-ling-guan-shan-yue", title: "关山月", author: "徐陵", authorSlug: "xu-ling", mode: "single" },
  { slug: "liu-zeng-shan-zhong-yin-shi", title: "留赠山中隐士", author: "周弘让", authorSlug: "zhou-hong-rang", mode: "single" },
  { slug: "hai-cao-tang-xun-chu-shi-di", title: "还草堂寻处士弟", author: "周弘正", authorSlug: "zhou-hong-zheng", mode: "single" },
  { slug: "yu-chang-an-shi-ji-pei-shang-shu", title: "遇长安使寄裴尚书", author: "江总", authorSlug: "jiang-zong", mode: "single" },
  { slug: "ru-she-shan-qi-xia-si", title: "入摄山栖霞寺", author: "江总", authorSlug: "jiang-zong", mode: "single" },
  { slug: "nan-hai-xun-cao-shi-zhai", title: "南还寻草市宅", author: "江总", authorSlug: "jiang-zong", mode: "single" },
  { slug: "bing-zhou-yang-chang-ban", title: "并州羊肠坂", author: "江总", authorSlug: "jiang-zong", mode: "single" },
  { slug: "yu-chang-an-gui-huan-yang-zhou-jiu-yue-jiu-ri-xing-wei-shan-ting-fu-yun", title: "于长安归还扬州九月九日行薇山亭赋韵", author: "江总", authorSlug: "jiang-zong", mode: "single" },
  { slug: "ku-lu-guang-da", title: "哭鲁广达", author: "江总", authorSlug: "jiang-zong", mode: "single" },
  { slug: "gui-yuan-pian", title: "闺怨篇", author: "江总", authorSlug: "jiang-zong", mode: "single" },
  { slug: "qiu-ri-bie-yu-zheng-yuan", title: "秋日别庾正员", author: "张正见", authorSlug: "zhang-zheng-jian", mode: "single" },
  { slug: "zhang-zheng-jian-guan-shan-yue", title: "关山月", author: "张正见", authorSlug: "zhang-zheng-jian", mode: "single" },
  { slug: "bei-shi-chu-guan", title: "被使出关", author: "何胥", authorSlug: "he-xu", mode: "single" },
  { slug: "chang-an-ting-bai-she", title: "长安听百舌", author: "韦鼎", authorSlug: "wei-ding", mode: "single" },
  { slug: "zhao-jun-ci", title: "昭君词", author: "陈昭", authorSlug: "chen-zhao", mode: "single" }
  ],
};
