import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import subsetFont from "subset-font";
import { collectSiteFontGlyphs } from "../src/lib/font-glyphs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// Regular(400) 为正文权威字重：Light(300) 在小字号下发虚，Regular 在桌面/移动一致。
// 子集源文件与 @font-face 声明字重对齐，消除字重不匹配造成的字形发虚。
const FONT_SOURCE = path.join(ROOT, "scripts/fonts/LXGWWenKai-Regular.ttf");
const FONT_SOURCE_URL =
  "https://github.com/lxgw/LxgwWenKai/releases/download/v1.521/LXGWWenKai-Regular.ttf";
const OUT_DIR = path.join(ROOT, "public/fonts/wenkai");
const CSS_OUT = path.join(ROOT, "src/fonts/wenkai.css");
const PATH_OUT = path.join(ROOT, "src/lib/wenkai-subset-path.generated.ts");
const MANIFEST_OUT = path.join(ROOT, "scripts/.cache/wenkai.manifest.json");
const VALIDATE_SCRIPT = path.join(ROOT, "scripts/validate-subset-cmap.py");

const MAX_FONT_BYTES = 400 * 1024;

async function ensureSourceFont(): Promise<void> {
  if (fs.existsSync(FONT_SOURCE)) {
    return;
  }

  fs.mkdirSync(path.dirname(FONT_SOURCE), { recursive: true });
  console.log(`Downloading LXGW WenKai Regular from ${FONT_SOURCE_URL}…`);
  const response = await fetch(FONT_SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Failed to download source font (${response.status})`);
  }

  fs.writeFileSync(FONT_SOURCE, Buffer.from(await response.arrayBuffer()));
}

function subsetFileName(glyphCount: number): string {
  return `wenkai-subset.${glyphCount}.woff2`;
}

function subsetPublicPath(glyphCount: number): string {
  return `/fonts/wenkai/${subsetFileName(glyphCount)}`;
}

function buildFontFaceCss(publicPath: string): string {
  // 不前置 local()：保证所有设备使用同一站点子集，避免本机霞鹜文楷
  // （可能为 Light/Regular/不同字重）劫持正文，导致桌面/移动字重不一致。
  return `@font-face {
  font-family: "LXGW WenKai";
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url(${publicPath}) format("woff2");
}
`;
}

function writeGeneratedPath(publicPath: string): void {
  const contents = `// Generated by scripts/generate-font-subset.ts — do not edit.
export const WENKAI_SUBSET_PATH = "${publicPath}";
`;
  fs.writeFileSync(PATH_OUT, contents);
}

function resolvePythonWithFontTools(): string {
  const candidates = [
    path.join(ROOT, ".venv-font/bin/python3"),
    "python3",
  ];

  for (const python of candidates) {
    try {
      execFileSync(python, ["-c", "from fontTools.ttLib import TTFont"], {
        stdio: ["ignore", "ignore", "ignore"],
      });
      return python;
    } catch {
      // try next candidate
    }
  }

  console.log("Installing fonttools for subset validation…");
  execFileSync(
    "python3",
    ["-m", "pip", "install", "--user", "--quiet", "-r", path.join(ROOT, "requirements.txt")],
    { stdio: "inherit" },
  );
  return "python3";
}

function validateSubsetCmap(fontPath: string, glyphs: number[]): void {
  const python = resolvePythonWithFontTools();
  execFileSync(python, [VALIDATE_SCRIPT, fontPath], {
    input: JSON.stringify(glyphs),
    stdio: ["pipe", "inherit", "inherit"],
  });
}

async function main(): Promise<void> {
  await ensureSourceFont();

  const glyphs = collectSiteFontGlyphs();
  const text = String.fromCodePoint(...glyphs);
  const fileName = subsetFileName(glyphs.length);
  const publicPath = subsetPublicPath(glyphs.length);
  const fontOut = path.join(OUT_DIR, fileName);

  console.log(`Collected ${glyphs.length} unique glyphs for font subset.`);

  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(CSS_OUT), { recursive: true });
  fs.mkdirSync(path.dirname(MANIFEST_OUT), { recursive: true });

  const sourceFont = fs.readFileSync(FONT_SOURCE);
  const subset = await subsetFont(sourceFont, text, {
    targetFormat: "woff2",
  });

  if (subset.byteLength > MAX_FONT_BYTES) {
    throw new Error(
      `Subset font is ${(subset.byteLength / 1024).toFixed(1)} KiB, exceeding ${MAX_FONT_BYTES / 1024} KiB limit`,
    );
  }

  fs.writeFileSync(fontOut, subset);
  validateSubsetCmap(fontOut, glyphs);

  fs.writeFileSync(CSS_OUT, buildFontFaceCss(publicPath));
  writeGeneratedPath(publicPath);

  const manifest = {
    glyphCount: glyphs.length,
    fontFile: fileName,
    publicPath,
    bytes: subset.byteLength,
  };
  fs.writeFileSync(MANIFEST_OUT, `${JSON.stringify(manifest, null, 2)}\n`);

  console.log(
    `Generated ${fileName}: ${(subset.byteLength / 1024).toFixed(1)} KiB for ${glyphs.length} glyphs.`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
