/**
 * Sui volume catalog config (原书卷十四·隋诗).
 * Generated by scripts/generate-sui-config.mjs — edit overrides there, then regenerate.
 */
export const SUI_CONFIG = {
  volume: "sui",
  dynasty: "隋",
  epubParts: [
    "text/part0020_split_004.html"
  ],
  expectedCount: 27,
  entries: [
  { slug: "yin-ma-chang-cheng-ku-xing-shi-cong-zheng-qun-chen", title: "饮马长城窟行示从征群臣", author: "炀帝", authorSlug: "yang-di", mode: "single" },
  { slug: "yang-di-bai-ma-pian", title: "白马篇", author: "炀帝", authorSlug: "yang-di", mode: "single" },
  { slug: "shan-zhai-du-zuo-zeng-xue-nei-shi-er-shou", title: "山斋独坐赠薛内史二首", author: "杨素", authorSlug: "yang-su", mode: "multi-chapter" },
  { slug: "zeng-xue-bo-zhou", title: "赠薛播州", author: "杨素", authorSlug: "yang-su", mode: "multi-chapter" },
  { slug: "you-liang-cheng", title: "游梁城", author: "卢思道", authorSlug: "lu-si-dao", mode: "single" },
  { slug: "xi-xi-yan", title: "昔昔盐", author: "薛道衡", authorSlug: "xue-dao-heng", mode: "single" },
  { slug: "jing-chou-yang-pu-she-shan-zhai-du-zuo", title: "敬酬杨仆射山斋独坐", author: "薛道衡", authorSlug: "xue-dao-heng", mode: "single" },
  { slug: "ren-ri-si-gui", title: "人日思归", author: "薛道衡", authorSlug: "xue-dao-heng", mode: "single" },
  { slug: "chu-sai", title: "出塞", author: "虞世基", authorSlug: "yu-shi-ji", mode: "single" },
  { slug: "ru-guan", title: "入关", author: "虞世基", authorSlug: "yu-shi-ji", mode: "single" },
  { slug: "he-zhou-ji-shi-you-jiu-jing", title: "和周记室游旧京", author: "孙万寿", authorSlug: "sun-wan-shou", mode: "single" },
  { slug: "zao-fa-yang-zhou-hai-wang-xiang-yi", title: "早发扬州还望乡邑", author: "孙万寿", authorSlug: "sun-wan-shou", mode: "single" },
  { slug: "dong-gui-zai-lu-l-er-cheng-yong", title: "东归在路率尔成咏", author: "孙万寿", authorSlug: "sun-wan-shou", mode: "single" },
  { slug: "bie-zhou-ji-shi", title: "别周记室", author: "王胄", authorSlug: "wang-zhou", mode: "single" },
  { slug: "bie-song-chang-shi", title: "别宋常侍", author: "尹式", authorSlug: "yin-shi", mode: "single" },
  { slug: "song-cai-jun-zhi-ru-shu", title: "送蔡君知入蜀", author: "孔德绍", authorSlug: "kong-de-shao", mode: "single" },
  { slug: "ye-su-huang-cun", title: "夜宿荒村", author: "孔德绍", authorSlug: "kong-de-shao", mode: "single" },
  { slug: "luo-ye", title: "落叶", author: "孔绍安", authorSlug: "kong-shao-an", mode: "single" },
  { slug: "bie-xu-yong-yuan-xiu-cai", title: "别徐永元秀才", author: "孔绍安", authorSlug: "kong-shao-an", mode: "single" },
  { slug: "song-bie", title: "送别", author: "陈子良", authorSlug: "chen-zi-liang", mode: "single" },
  { slug: "qi-xi-kan-xin-fu-ge-xiang-ting-che", title: "七夕看新妇隔巷停车", author: "陈子良", authorSlug: "chen-zi-liang", mode: "single" },
  { slug: "fu-de-yan-xue-wu-jie-gou", title: "赋得岩穴无结构", author: "王申礼", authorSlug: "wang-shen-li", mode: "single" },
  { slug: "he-ru-jing", title: "和入京", author: "吕让", authorSlug: "lv-rang", mode: "single" },
  { slug: "ming-yu-qing-cong-jun-xing", title: "从军行", author: "明馀庆", authorSlug: "ming-yu-qing", mode: "single" },
  { slug: "shu-ping-feng-shi", title: "书屏风诗", author: "大义公主", authorSlug: "da-yi-gong-zhu", mode: "single" },
  { slug: "song-bie-shi", title: "送别诗", author: "无名氏", authorSlug: "wu-ming-shi", mode: "single" },
  { slug: "ji-ming-ge", title: "鸡鸣歌", author: "无名氏", authorSlug: "wu-ming-shi", mode: "single" }
  ],
};
